InventoryManager/InventoryManager/Controllers/ItemsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PagedList;

namespace InventoryManager.Controllers
{
    public class ItemsController : BaseController
    {
        // GET: Items
        public ActionResult Index(Guid guid, string sortOrder, string currentFilter, string searchString, int? page)
        {
            // get active items for this store only
            var tbl_Items = db.tbl_Items.Where(x => x.StoreGuid == guid && x.Active == true && x.Quality > 0 && (x.DateTrashed >= DateTime.Now || x.DateTrashed == null)).Include(t => t.tbl_Stores);

            // set store in session
            currentStore = db.tbl_Stores.Where(x => x.Guid == guid).FirstOrDefault();
            System.Web.HttpContext.Current.Session["currentStore"] = currentStore;
            ViewBag.Store = currentStore;

            // Search Name
            if (!String.IsNullOrEmpty(searchString))
            {
                tbl_Items = tbl_Items.Where(s => s.Name.Contains(searchString) || s.Category.Contains(searchString));
            }
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            // sorting
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder == "Name" ? "Name_desc" : "Name";
            ViewBag.CategorySortParm = sortOrder == "Category" ? "Category_desc" : "Category";
            ViewBag.SellInSortParm = sortOrder == "SellIn" ? "SellIn_desc" : "SellIn";
            ViewBag.QualitySortParm = sortOrder == "Quality" ? "Quality_desc" : "Quality";
            ViewBag.LegendarySortParm = sortOrder == "Legendary" ? "SellIn_desc" : "Legendary";
            ViewBag.BetterWithAgeSortParm = sortOrder == "BetterWithAge" ? "BetterWithAge_desc" : "BetterWithAge";
            switch (sortOrder)
            {
                case "Name":
                    tbl_Items = tbl_Items.OrderBy(s => s.Name);
                    break;
                case "Name_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.Name);
                    break;
                case "Category":
                    tbl_Items = tbl_Items.OrderBy(s => s.Category);
                    break;
                case "Category_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.Category);
                    break;
                case "SellIn":
                    tbl_Items = tbl_Items.OrderBy(s => s.SellIn);
                    break;
                case "SellIn_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.SellIn);
                    break;
                case "Quality":
                    tbl_Items = tbl_Items.OrderBy(s => s.Quality);
                    break;
                case "Quality_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.Quality);
                    break;
                case "Legendary":
                    tbl_Items = tbl_Items.OrderBy(s => s.Legendary);
                    break;
                case "Legendary_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.Legendary);
                    break;
                case "BetterWithAge":
                    tbl_Items = tbl_Items.OrderBy(s => s.BetterWithAge);
                    break;
                case "BetterWithAge_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.BetterWithAge);
                    break;
                default:
                    tbl_Items = tbl_Items.OrderBy(s => s.Name);
                    break;
            }

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(tbl_Items.ToPagedList(pageNumber, pageSize));
        }

        // GET: Trash Items
        public ActionResult Trash(Guid guid, string sortOrder, string currentFilter, string searchString, int? page)
        {
            // get quality = 0 items for this store only
            var tbl_Items = db.tbl_Items.Where(x => x.StoreGuid == guid && x.Active == true && x.Quality == 0).Include(t => t.tbl_Stores);

            // set store in session
            currentStore = db.tbl_Stores.Where(x => x.Guid == guid).FirstOrDefault();
            System.Web.HttpContext.Current.Session["currentStore"] = currentStore;
            ViewBag.Store = currentStore;

            // Search Name
            if (!String.IsNullOrEmpty(searchString))
            {
                tbl_Items = tbl_Items.Where(s => s.Name.Contains(searchString) || s.Category.Contains(searchString));
            }
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            // sorting
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder == "Name" ? "Name_desc" : "Name";
            ViewBag.CategorySortParm = sortOrder == "Category" ? "Category_desc" : "Category";
            ViewBag.SellInSortParm = sortOrder == "SellIn" ? "SellIn_desc" : "SellIn";
            ViewBag.QualitySortParm = sortOrder == "Quality" ? "Quality_desc" : "Quality";
            ViewBag.LegendarySortParm = sortOrder == "Legendary" ? "SellIn_desc" : "Legendary";
            ViewBag.BetterWithAgeSortParm = sortOrder == "BetterWithAge" ? "BetterWithAge_desc" : "BetterWithAge";
            switch (sortOrder)
            {
                case "Name":
                    tbl_Items = tbl_Items.OrderBy(s => s.Name);
                    break;
                case "Name_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.Name);
                    break;
                case "Category":
                    tbl_Items = tbl_Items.OrderBy(s => s.Category);
                    break;
                case "Category_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.Category);
                    break;
                case "SellIn":
                    tbl_Items = tbl_Items.OrderBy(s => s.SellIn);
                    break;
                case "SellIn_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.SellIn);
                    break;
                case "Quality":
                    tbl_Items = tbl_Items.OrderBy(s => s.Quality);
                    break;
                case "Quality_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.Quality);
                    break;
                case "Legendary":
                    tbl_Items = tbl_Items.OrderBy(s => s.Legendary);
                    break;
                case "Legendary_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.Legendary);
                    break;
                case "BetterWithAge":
                    tbl_Items = tbl_Items.OrderBy(s => s.BetterWithAge);
                    break;
                case "BetterWithAge_desc":
                    tbl_Items = tbl_Items.OrderByDescending(s => s.BetterWithAge);
                    break;
                default:
                    tbl_Items = tbl_Items.OrderBy(s => s.Name);
                    break;
            }

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(tbl_Items.ToPagedList(pageNumber, pageSize));
        }

        // clear all trash
        public ActionResult TrashAll(Guid guid)
        {
            // get trash items for this store only
            var tbl_Items = db.tbl_Items.Where(x => x.StoreGuid == guid && x.Active == true && x.Quality == 0).Include(t => t.tbl_Stores);
            
            foreach (tbl_Items item in tbl_Items.ToList())
            {
                // deactive trash items
                item.Active = false;
                item.DateTrashed = DateTime.Now;
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
            }

            tbl_Items = db.tbl_Items.Where(x => x.StoreGuid == guid && x.Active == true && x.Quality == 0).Include(t => t.tbl_Stores);
            return RedirectToAction("Trash", new { guid = currentStore.Guid });
        }

        // clear all trash
        public ActionResult Sell(Guid guid)
        {
            // get trash items for this store only
            var tbl_Items = db.tbl_Items.Where(x => x.Guid == guid);

            foreach (tbl_Items item in tbl_Items.ToList())
            {
                // deactive sold items
                item.Active = false;
                item.DateSold = DateTime.Now;
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index", new { guid = currentStore.Guid });
        }

        // to run the Daily Update Job manually
        public ActionResult DailyUpdate()
        {
            JobSchedulerController JS = new JobSchedulerController();
            if (JS.DailyUpdateAlgorithm(true))
            {
                // ran successfully
                return RedirectToAction("Admin", "Home", new { message = "Daily Update Successfully Run!" });
            }
            else
            {
                // failed to complete
                tbl_DailyUpdateLog log = db.tbl_DailyUpdateLog.OrderByDescending(x => x.DateTime).FirstOrDefault();
                string msg = "Daily Update Failed! Only runs once per day! Last Run: " + log.DateTime;
                return RedirectToAction("Admin", "Home", new { message = msg });
            } 
        }


        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

InventoryManager/InventoryManager/Views/Items/Create.cshtml
@model InventoryManager.tbl_Items

@{
    ViewBag.Title = "Create New Item";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New Item", "Create") | @Html.ActionLink("Upload Inventory", "Upload") | @Html.ActionLink("Trash", "Trash", new { guid = ViewBag.Store.Guid })
</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SellIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellIn, "", new { @class = "text-danger" })
                <a href="#" data-toggle="tooltip" title="Days in which item needs to be sold." class="btn btn-default">?</a>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quality, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Legendary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Legendary)
                    @Html.ValidationMessageFor(model => model.Legendary, "", new { @class = "text-danger" })
                    <a href="#" data-toggle="tooltip" title="Is this item Legendary?  Never decreases in Quality and never has to be Sold." class="btn btn-default">?</a>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BetterWithAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.BetterWithAge)
                    @Html.ValidationMessageFor(model => model.BetterWithAge, "", new { @class = "text-danger" })
                    <a href="#" data-toggle="tooltip" title="Does the Quality of this item increase with Age?" class="btn btn-default">?</a>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Inventory", "Index", new { guid = ViewBag.Store.Guid })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/InventoryManager")
}

InventoryManager/InventoryManager/Views/Items/Edit.cshtml
@model InventoryManager.tbl_Items

@{
    ViewBag.Title = "Edit " + Model.Name;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Guid)
        @Html.HiddenFor(model => model.StoreGuid)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellIn, htmlAttributes: new { @class = "control-label col-md-2" })
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.SellIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellIn, "", new { @class = "text-danger" })
                <a href="#" data-toggle="tooltip" title="Days in which item needs to be sold." class="btn btn-default">?</a>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quality, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Legendary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Legendary)
                    @Html.ValidationMessageFor(model => model.Legendary, "", new { @class = "text-danger" })
                    <a href="#" data-toggle="tooltip" title="Is this item Legendary?  Never decreases in Quality and never has to be Sold." class="btn btn-default">?</a>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BetterWithAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.BetterWithAge)
                    @Html.ValidationMessageFor(model => model.BetterWithAge, "", new { @class = "text-danger" })
                    <a href="#" data-toggle="tooltip" title="Does the Quality of this item increase with Age?" class="btn btn-default">?</a>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.DateCreated)
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" }) 
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                    <a href="#" data-toggle="tooltip" title="Unchecking this box will remove this item from your inventory." class="btn btn-default">?</a>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Inventory", "Index", null, new { guid = Model.StoreGuid }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/InventoryManager")
}

InventoryManager/InventoryManager/Views/Items/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<InventoryManager.tbl_Items>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = ViewBag.Store.Name + "'s Inventory";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New Item", "Create") | @Html.ActionLink("Upload Inventory", "Upload") | @Html.ActionLink("Trash", "Trash", new { guid = ViewBag.Store.Guid })
</p>

@using (Html.BeginForm())
{
    <p>
        <big>@Html.Label("Search by Name or Category", htmlAttributes: new { @class = "control-label col-md-3", align = "right" }) &nbsp;&nbsp; </big>
        @Html.TextBox("searchString", null, new { @class = "form-control col-md-3" }) &nbsp;&nbsp;
        <input type="submit" value="Search" class="btn btn-default" />

    </p>
}
<br />
<div style="overflow-x:auto;">
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Category", "Index", new { sortOrder = ViewBag.CategorySortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Sell In", "Index", new { sortOrder = ViewBag.SellInSortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Quality", "Index", new { sortOrder = ViewBag.QualitySortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Legendary", "Index", new { sortOrder = ViewBag.LegendarySortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Better With Age", "Index", new { sortOrder = ViewBag.BetterWithAgeSortParm, guid = ViewBag.Store.Guid })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SellIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quality)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Legendary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BetterWithAge)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Guid }) | @Html.ActionLink("Sell", "Sell", new { guid = item.Guid })
                </td>
            </tr>
        }

    </table>
</div>

<br />

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, guid = ViewBag.Store.Guid }))

InventoryManager/InventoryManager/Views/Items/Trash.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<InventoryManager.tbl_Items>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = ViewBag.Store.Name + "'s Trash";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New Item", "Create") | @Html.ActionLink("Upload Inventory", "Upload") | @Html.ActionLink("Trash", "Trash", new { guid = ViewBag.Store.Guid })
</p>

<p>@Html.ActionLink("Clear All Trash", "TrashAll", new { guid = ViewBag.Store.Guid }, new { @class ="btn btn-default"  })</p>

<div style="overflow-x:auto;">
    <table class="table">
        <tr>
        <tr>
            <th>
                @Html.ActionLink("Name", "Trash", new { sortOrder = ViewBag.NameSortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Category", "Trash", new { sortOrder = ViewBag.CategorySortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Sell In", "Trash", new { sortOrder = ViewBag.SellInSortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Quality", "Trash", new { sortOrder = ViewBag.QualitySortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Legendary", "Trash", new { sortOrder = ViewBag.LegendarySortParm, guid = ViewBag.Store.Guid })
            </th>
            <th>
                @Html.ActionLink("Better With Age", "Trash", new { sortOrder = ViewBag.BetterWithAgeSortParm, guid = ViewBag.Store.Guid })
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SellIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quality)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Legendary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BetterWithAge)
                </td>
            </tr>
        }
    </table>
</div>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, guid = ViewBag.Store.Guid }))

<div>
    @Html.ActionLink("Back to Inventory", "Index", new { guid = ViewBag.Store.Guid })
</div>

InventoryManager/InventoryManager/Views/Items/Upload.cshtml
@model InventoryManager.tbl_Items

@{
    ViewBag.Title = "Upload Inventory";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New Item", "Create") | @Html.ActionLink("Upload Inventory", "Upload") | @Html.ActionLink("Trash", "Trash", new { guid = ViewBag.Store.Guid})
</p>

<div class="form-horizontal">
    <hr />

    <div>
        <p><b>Instructions:</b> Copy and Paste your inventory list into the form below.<br/><br />
            <b>Format:</b><br />
            &nbsp;&nbsp;&nbsp;Name, Category, Sell In, Quality<br />
            &nbsp;&nbsp;&nbsp;Name, Category, Sell In, Quality<br />
            &nbsp;&nbsp;&nbsp;Name, Category, Sell In, Quality<br />
            &nbsp;&nbsp;&nbsp;<b>...</b>
        </p>
    </div>

    @using (Html.BeginForm("Upload", "Items", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
    <div>

        <div class="form-group">
            @Html.Label("Inventory List", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextArea("file", "", new { type = "text", @class = "form-control", @rows = "10" }) <br />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>

        <div>
            <big><i><p>@ViewBag.Message</p></i></big>
        </div>

    </div>
    }
</div>

<br/>

<div>
    @Html.ActionLink("Back to Inventory", "Index", null, new { guid = ViewBag.Store.Guid }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}